# 📗 Day 4 — Selecting Data

**Roadmap:** Selecting Columns → `iloc` → `loc` → Boolean Indexing → 🚢 Titanic

📂 **Datasets:** `tips.csv` and `titanic.csv` — keep both in the same folder as this notebook.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/shailesh/Desktop/vedam_Sem3_ml/Data/tip.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

---
### 🔁 Recap — Day 3

**R1** How many rows and columns does `df` have? Print the column names.

**R2** Which day has the most bills? How many different days are there?

In [ ]:
# R1

In [ ]:
# R2

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

---
## 1️⃣ Selecting Columns

> **Flow:** `df['col']` → Series · `df[['col']]` → DataFrame · many columns · new column

In [ ]:
# selecting many columns
x=df['day']
print(x.shape)
y=df[['day']]
print(y.shape)

(244,)
(244, 1)

In [ ]:
# making a new column
#Add a column called `bill_per_person` — the bill divided by the number of people

### 🧩 Try these

**1.1** Fill the blank to get three columns at once.
```python
df[____'total_bill', 'tip', 'day'____]
```

In [ ]:
# 1.1
#df[____'total_bill', 'tip', 'day'____]

**1.2** How much did each person pay? Fill the blank.

```python
df['bill_per_person'] = df['total_bill'] ____ df['size']
```

In [ ]:
# 1.2
#df['bill_per_person'] = df['total_bill'] ____ df['size']

**1.3** Add a column called `total_paid` — the bill plus the tip. Write the full line.
```python
df['total_paid'] = ____
```

In [ ]:
# 1.4

### 🔧 Break my code

Both lines are wrong. Find the mistake without running them.

```python
df.shape()
df['total_bill', 'tip']
```

In [ ]:
# what is wrong?

---
## 2️⃣ `iloc` — selecting by position

You did this in NumPy. Here we use it to pick **rows**.

> **Flow:** one row → many rows → rows and columns together

In [ ]:
# iloc — one row, then a slice of rows

In [ ]:
# iloc — rows and columns by position

### 🧩 Try these

**2.1** Fill the blanks.

```python
df.iloc[____]      # the 6th row
df.iloc[____]      # the last row
df.iloc[____]      # the first 5 rows
```

In [ ]:
# 2.1

**2.2** Show only `day` and `total_bill`. Fill the blank.
```python
print(list(df.columns))     # run this first

df.iloc[10:15, ____]
```

In [ ]:
# 2.2

---
## 3️⃣ `loc` — selecting by label

> **Flow:** row by label → rows and columns by name → **the slicing difference** ⭐

In [ ]:
# loc — one row by its label

In [ ]:
# loc — rows and columns by name

### ✋ Guess first, then run

`df.iloc[2:5]` and `df.loc[2:5]`

**Same number of rows, or different?** Write your guess as a comment first.

In [ ]:
# my guess:

# now run both

### 🧩 Try these

**3.1** Find the row labelled 100. Which day was it, and what was the tip?

In [ ]:
# 3.1

**3.2** Both lines should give the same 11 rows. Fill the blank.
```python
df.loc[10:20]        # 11 rows
df.iloc[10:____]     # make this 11 too
```

In [ ]:
# 3.2

---
## 4️⃣ Boolean Indexing

So far you knew **which** row you wanted. Now you don't — you only know **what must be true** about it.

> **Flow:** the True/False list → use it to filter → count → two conditions with `&` and `|`

In [ ]:
# the condition on its own — True/False for every row

In [ ]:
# use it to filter

In [ ]:
# count how many matched

In [ ]:
# two conditions — & and |

### 🧩 Try these

**4.1** Bills where the tip was above 6. Fill the blanks, then count them.
```python
df[df[____] ____ 6]
```

In [ ]:
# 4.1

**4.3** Fill the blanks.
```python
df[(df['total_bill'] > 30) ____ (df['tip'] > 5)]      # both true
df[(df['time'] == 'Dinner') ____ (df['size'] > 4)]    # either one true
```

In [ ]:
# 4.3

### 🔧 Break my code

All three are wrong. Find the mistakes.

```python
df[df['tip' > 6]]
df[df['size'] > 2 & df['tip'] > 4]
df.iloc[0, 'tip']
```

In [ ]:
# what is wrong?

---
## 5️⃣ Putting it together — `loc` with a condition

**Rows chosen by a condition. Columns chosen by name. One line.**

This is the most common line in all of Pandas.

In [ ]:
# loc[ condition , columns ]

**5.1** Bills with a tip above 6 — show only `day` and `tip`. Fill both blanks.
```python
df.loc[____, ____]
```

In [ ]:
# 5.1

**5.3** What was the average `total_bill` on Sundays? ⭐

In [ ]:
# 5.3

---
# 🚢 Titanic

April 1912. The Titanic sank. Some people survived, some did not.
Who survived was not random. Let's find out who.

Each box has two questions. I will solve the first one. You solve the second one.

In [ ]:
t = pd.read_csv('titanic.csv')
print(t.shape)
t.head()


### How many passengers were in first class?

In [ ]:
#  How many passengers were above age 60?

###  How many men were travelling alone?

In [ ]:
# How many children under 10 were in third class?

### How many men over 40 survived?

In [ ]:
# How many women under 30 in second class survived?

###  Out of all the men, what percentage survived?

In [ ]:
# Out of everyone who paid more than 50 for their ticket, what percentage survived?

### ⚠️ One problem with all of that

Run this.

In [ ]:
t['age'].isnull().sum()

Every answer that used `age` quietly **left these passengers out**.
They were not counted as over 40, and not counted as under 40 either. They just disappeared.

**Tomorrow: what do we do about them?**

### 🔍 Your own question

Write **one line** that finds any group you find interesting. Then tell the class what you got.

In [ ]:
# my question:

---
# ⭐ Bonus — shortcuts (only if we have time)

Everything below does something you can **already do**. These are just shorter ways.
A shortcut only makes sense once you know the long way.

## `isin()` — instead of a long chain of `|`

The long way:
```python
df[(df['day'] == 'Sat') | (df['day'] == 'Sun')]
```

In [ ]:
# the short way — isin()

**B1** Find all Lunch bills from Thursday or Friday, using `isin()`.

In [ ]:
# B1

## `between()` — instead of two conditions with `&`

The long way:
```python
df[(df['total_bill'] > 20) & (df['total_bill'] < 30)]
```

In [ ]:
# the short way — between()

**B2** Find bills where the tip was between 3 and 5.

In [ ]:
# B2

## `sort_values()` and `nlargest()`

In [ ]:
# sort by a column, largest first

**B3** Find the 5 biggest tips.

**B4** Sort by `total_bill`, largest first, and save it as `top`.
Now run `top.iloc[0]` and `top.loc[0]`. **Different rows?** Explain why in a comment. ⭐

In [ ]:
# B3

In [ ]:
# B4

## `reset_index()` — fixing labels after filtering

In [ ]:
sat = df[df['day'] == 'Sat']

sat.iloc[0]      # works — first Saturday bill
# sat.loc[0]     # uncomment this. It fails. Why?

In [ ]:
# fix it with reset_index(drop=True)

---
## 📌 Recap

| | `loc` | `iloc` |
|---|---|---|
| Picks by | **label** (name) | **position** (number) |
| Slice end | **included** | **not included** |
| Columns given as | names | numbers |
| Takes a condition | **yes** | no |

**Boolean indexing:** write a condition, get True/False for every row, keep the True ones.
Two conditions need `&` or `|`, with **brackets around each one**.

**🔜 Day 5 — Data Cleaning:** those 177 missing ages · duplicates · sorting · and a dataset made from **your own** answers 📊

## https://shorturl.at/QB5Uj